### ISSUE TITLE
配置下来花了多少钱

### ISSUE THREAD

**Issue by liupeng110** [bigbearishappy/BBear_balance_car#2]
配置下来花了多少钱
组装完成的多少钱

**Comment by bigbearishappy** [comment]
整个组装好大概需要一百多点

**Comment by liupeng110** [comment]
你qq多少呀，我也想组装一个 智能小车 没有弄过

**Comment by liupeng110** [comment]
已经买了两个电机+轮子那种组合 了，不知道该怎么驱动

**Comment by bigbearishappy** [comment]
软硬件方面需要的资料在工程里面都有的，你先看看，平常qq看得少，你如果有什么问题就邮箱联系我吧
BBear_mail@163.com

**Comment by liupeng110** [comment]
好的多谢，
我想做的 跟你那个有点不太一样，
我想用一部带otg功能的旧android手机作为小车控制中心
用otg跟单片机或电机驱动模块通信   
手机有摄像头,音频模块,蓝牙模块,wifi模块,陀螺仪模块,还能装sim卡 
如果全部用上的话 非常6的

**Comment by bigbearishappy** [comment]
你这个创意有意思，你可以就在现有基础上增加单片机与手机之间的数据通讯~ 这样以来开发的重点就是手机端的应用与驱动开发了~

**Comment by cos12a** [comment]
可是打印文件在手機上處理,這些還需要很多的軟件支持.






Best regards.
YZLuo
Mail:cos12a@163.com


在2017年07月7日 11:19，BBear<notifications@github.com> 写道：

你这个创意有意思，你可以就在现有基础上增加单片机与手机之间的数据通讯~ 这样以来开发的重点就是手机端的应用与驱动开发了~

**Comment by liupeng110** [comment]
是啊，我也是这样想的   就是没做过   有点苦逼，这样做的话  
ios/android端都可以 控制小车   买个4g流量卡 还可以远程控制  
以此类推还可以做个类似的无人机   
我感觉用arduino开发板太坑了    

你有这方面的资料么

**Comment by liupeng110** [comment]
打印什么文件?

**Comment by bigbearishappy** [comment]
安卓方面的开发我了解的很少，无法给你提供什么帮助~~

**Comment by liupeng110** [comment]
安卓方面倒是不用提供什么帮助，主要是单片机那边我不太熟悉

**Comment by liupeng110** [comment]
想要跟电机的驱动模块通信有哪些方式？
这个模块应该是带单片机的吧

**Comment by bigbearishappy** [comment]
电机驱动模块一般是没有单片机的~

**Comment by liupeng110** [comment]
这样，那我大概知道了  多谢了 ，那我用otg跟单片机通信  
单片机控制电机驱动  就可以了
